### PR TITLE
Bump phpunit version

### LINKED ISSUE #2: Composer conflicts with my phpunit version
Hello!

When installing this lib on my project, I get an error because my phpunit version is on an earlier version than this lib.

Maybe we could bump the version?

Thanks

### PR DESCRIPTION
**Pull request by janjitsu**
closes #2

### CODE REVIEW

**Comment by vinyvicente** [comment]
@janjitsu your pull request broken.

**Comment by janjitsu** [comment]
@vinyvicente  can you help me fixit ? should I just run composer against php 7.0, that's it? i'm using php 7.1

**Comment by janjitsu** [comment]
@vinyvicente any tips? I've ran composer against php 7.0 and also got errors

**Comment by vinyvicente** [comment]
@janjitsu the problem is with doctrine dbal version. Try on composer 2.5.* || 2.6.*

**Comment by janjitsu** [comment]
@vinyvicente I've upgraded to dbal 2.6, but unfortunately it requires php 7.1 so I removed it from travis-ci. I guess this is a breaking change and we should bump library version, right?

https://packagist.org/packages/doctrine/dbal#v2.6.0

**Comment by vinyvicente** [comment]
see last comment :)

**Pull request merged**
